data_input_folder: ./data_input/
data_input_file: works.csv  
data_output_folder: ./data_output/
sdg_threshold: 0.98 # The threshold a value needs to reach to give an SDG label
classifier_url: "https://aurora-sdg.labs.vu.nl/classifier/classify/aurora-sdg-multi" # options are: "https://aurora-sdg.labs.vu.nl/classifier/classify/aurora-sdg-multi" (a faster model, suitable for estimating some top results, but less suitable for threshold values in data science) or "https://aurora-sdg.labs.vu.nl/classifier/classify/aurora-sdg" (a slower model, but more suitable for setting threshold values for filtering in data science)
rate_limit: 0.2 # Default rate limit of the API is set to 0.2 That is 5 requests per second.